apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../../base/vanilla/components/cert-manager
  - letsencrypt-issuer.yaml
  - cloudflare-token.yaml

patches:
  - path: self-signed-ca-cert.yaml